% Author: Popov Dmitry
% Innopolis University
% Industrial Robotics
% Homework 5
function out = FK_7DOF(Q,Pi,Tbase,Ttool)
T = Tbase*Rz(Q(1)+Pi(1))*...
    Ry(Q(2)+Pi(2))*Tz(Pi(8))*...
    Rz(Q(3)+Pi(3))*...
    Ry(Q(4)+Pi(4))*Tz(Pi(9))*...
    Rz(Q(5)+Pi(5))*...
    Ry(Q(6)+Pi(6))*...
    Rz(Q(7)+Pi(7))*Ttool;
out = T; 
end